image:
  file: .gitpod.Dockerfile

tasks:
  - name: Build Dependencies
    init: |
      cd $GITPOD_REPO_ROOT
      mkdir -p build
      cd build
      cmake ..
      make -j4

vscode:
  extensions:
    - "ms-vscode.cpptools" # C++ IntelliSense extension
